import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import bg from '@/public/Dark.svg' 
import Image from "next/image";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        // style={{
        //   backdropFilter: "blur(20px)",
        //   backgroundColor: "rgba(13, 9, 10, 0.5)",
        // }}
        className={`${inter.className} w-screen h-screen bg-Dark  bg-fixed bg-center bg-no-repeat bg-cover no-scrollbar`}
      >
        {/* <Head>
          <link rel="preload" href={bg} as="image" />
        </Head> */}
        {/* <Image src={bg} fill objectFit="cover"  alt="bg" className="z-[-1]"/> */}
        {children}
      </body>
    </html>
  );
}
