import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "../components/Dashboard/Sidebar/Sidebar";
import Navbar from "../components/Dashboard/Navbar/Navbar";
import ContentWrapper from "./ContentWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
      <section
        className={`${inter.className} w-screen h-screen bg-Dark bg-fixed bg-center bg-no-repeat bg-cover overflow-y-hidden`}
      >
        <ContentWrapper>
          {children}
        </ContentWrapper>
      </section>
  );
}
